build:
	@cd gaps && make build
	@cd gaps-pkg && make build
	@cd gaps-repo && make build

cleanbuild:
	@cd gaps && make cleanbuild
	@cd gaps-pkg && make cleanbuild
	@cd gaps-repo && make cleanbuild

clean:
	@cd gaps && make clean
	@cd gaps-pkg && make clean
	@cd gaps-repo && make clean

package:
	@cd gaps && make package
	@cd gaps-pkg && make package
	@cd gaps-repo && make package
